version: "3.6"
services:
  executor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GITHUB_CLIENT_ID: "db"
      GITHUB_CLIENT_SECRET: "root"
    restart: always
    container_name: executor_service
    ports:
      - "8080:8080"
    tty: true

